### ISSUE TITLE
滑塊位於某直線上符號式推導

### ISSUE THREAD

**Issue by mdecourse** [pyslvs/pyslvs.github.io#11]
參考資料

https://mde2a1.kmol.info/artifact/7dc04f7ff58ae656

b 為固定點，be 為固定長度連桿，
e 點為滑塊位置，cd 為某條直線，
而約束條件為 e 在 cd 直線上滑動，
目前 Pyslvs 似乎 cd 必須為固定直線，
但 cd 應該可以是在某一運動的連桿上滑動，
之後若再延伸，甚至可以在運動中的曲線滑槽中滑動。

另外，針對連桿為油壓缸的模擬條件為，
該直線連桿可在一定範圍內變動長度，
並以不同於固定長度連桿的油壓缸圖示代表。

**Comment by KmolYuan** [comment]
調校 Sketch Solve 後成功模擬 Inverted slider 範例，其他滑塊範例也都順利模擬，不過三角形推導還未完成。

![inverted slider](https://user-images.githubusercontent.com/10264720/44296834-8c0c3700-a2f8-11e8-8ab6-6fe8a5fd10c5.gif)

本範例若是迭代間格太長（>1度）會造成路徑預覽錯誤，此部分只能改動路徑錄製的間隔設定，會稍微增加運算負荷。

**Comment by mdecourse** [comment]
Good, 但可能要使用 piston 的外型來呈現 slider, 且明確顯示滑槽的兩個端點, 模擬流程會比較接近實體組立.

**Comment by mdecourse** [comment]
# 凸輪的應用

若滑塊可以約束在特定曲線範圍運行, 就可導入凸輪元件

Conceptual design and dimensional synthesis of cam-linkage mechanisms for gait rehabilitation

https://www.sciencedirect.com/science/article/pii/S0094114X16300842
