### ISSUE TITLE
Python versions

### ISSUE THREAD

**Issue by KmolYuan** [pyslvs/pyslvs.github.io#15]
PyInstaller
---

官方問題回報：https://github.com/pyinstaller/pyinstaller/issues/3399

可攜的 Python 版本若為 3.7，目前測試 SWIG 與 Cython 的程式庫運作正常。

當前 3.7 無法包裝獨立可執行檔案，應等待 PyInstaller 支援。

AppImage
---

透過虛擬編譯測試：<https://travis-ci.org/KmolYuan/Pyslvs-PyQt5>

可在 Ubuntu 16.04 線上虛擬機中成功包裝 Python 3.7 的 AppImage。

並且在 Ubuntu 18.04 實體機測試包裝 Python 3.6 的 AppImage 成功。

---

另外 Pyslvs 18.08 中將提升版本需求為 Python 3.6，以支援 formatted string ([PEP 498])。

[PEP 498]: https://www.python.org/dev/peps/pep-0498/#raw-f-strings

**Comment by mdecourse** [comment]
下學期的可攜系統分別使用 Python 3.6.5 ([Qt](https://drive.google.com/file/d/12BLN4daAPlO1KjCTDFi1kqJZ6f5k7Y5k/view?usp=sharing))與 Python 3.7.0 ([p37](https://drive.google.com/file/d/1DWtyoUhl8CycKJ8uulB3viRXE39KqpE1/view?usp=sharing))

可攜系統: https://bit.ly/2vPAog6

其中 [p37](https://drive.google.com/file/d/1DWtyoUhl8CycKJ8uulB3viRXE39KqpE1/view?usp=sharing) 在製作時, 無法直接安裝 pyqt5-tools, 而是使用 Python 3.6.5 中的目錄內容.

[Qt](https://drive.google.com/file/d/12BLN4daAPlO1KjCTDFi1kqJZ6f5k7Y5k/view?usp=sharing) 解開後需要 21GB, 包含 Qt Creator, 除了可以開發 Qt5 視窗程式外, 也能支援最新的 mobile 觸控程式.

**Comment by KmolYuan** [comment]
Pyslvs 已正式支援 Mac OS (https://github.com/KmolYuan/Pyslvs-PyQt5/issues/17)。

Mac OS 的獨立可執行檔案使用 PyInstaller 包裝，不過將會打包成兩種格式：Unix executable file 和 app format。

+ Unix executable file 在檔案瀏覽器 Finder 中得使用 Bash 執行。
+ app format 可以使用 open 執行（同在 Finder 中點擊），但是無法用 bash 執行（因為是壓縮檔），導致無法下參數，可做為 release 版本發布。
