### ISSUE TITLE
Pyslvs 的設計方法

### ISSUE THREAD

**Issue by KmolYuan** [pyslvs/pyslvs.github.io#18]
Pyslvs 主要特色
---

![computer_aid_design_method_watermark](https://user-images.githubusercontent.com/10264720/45019431-e75f5880-b05e-11e8-83b7-03ea93e659d9.png)

三階段設計：

+ Structure Synthesis: 結構合成
+ Dimensional Synthesis: 尺寸合成
+ Kinematic Simulation: 運動模擬

其中包含順序流程與反向分析。

為求統一，程式內的表示式想換成 PMKS 表示法（目前只有運動模擬採用），以除去開發上可能造成的誤解與不便。

尺寸合成改進
---

目標：丟入一組 PMKS 表示法，輸入各項參數範圍，產生全新的同類型連桿機構。

1. 使用 PMKS 表示法將可能無法有效看到連桿尺寸（4 接頭以上連桿），這部分值得考慮。

    + 解 1：由使用者調整連桿尺寸的配置方案。（開發時間稍長）
    + 解 2：全部使用座標作為亂數生成對象，另外加入約束。（有不穩定的結果、運算效率差）

1. 尺寸合成中想改為**三角形法** + **Sketch Solve** 的方式做驗證，以適應各種機構的解題。在尺寸合成演算法中使用數值分析作為驗證是否能成為有效的方案呢？

**Comment by pyslvs** [comment]
# AutoWIG

請在 SWIG 與 Cython 章節中, 納入此篇研究的討論, 並嘗試引用

[AutoWIG - automatic generation of python bindings for Cpp libraries.pdf](https://github.com/pyslvs/pyslvs.github.io/files/2441549/AutoWIG.-.automatic.generation.of.python.bindings.for.Cpp.libraries.pdf)
https://github.com/StatisKit/AutoWIG

**Comment by KmolYuan** [comment]
YAML 是一種標記性語言，設計於儲存樹狀與鏈狀資料結構。身為標記性語言，此種文本檔案格式可以更容易閱讀與適應版次管理系統。

透過 PyYAML 套件，Python 的內建資料容器可以輕鬆讀寫 YAML 格式。

Pyslvs 可以將其取代原本的 SQL 檔案格式，依附到 git 或 Fossil 中。

**Comment by KmolYuan** [comment]
Pyslvs 的技術架構圖：

![pyslvs_structure_ch](https://user-images.githubusercontent.com/10264720/50326801-35716c80-0527-11e9-8fb3-adc026aa3c11.png)

Pyslvs 的電腦輔助設計流程：

![creative-process-new](https://user-images.githubusercontent.com/10264720/50326827-4f12b400-0527-11e9-949c-34d33b55e7e9.png)
