### ISSUE TITLE
18.9.0 版本無法正確存檔

### ISSUE THREAD

**Issue by mdecourse** [pyslvs/pyslvs.github.io#19]
以 [p37_adv](https://drive.google.com/file/d/1WOGsDH_rVWBJJ5QI6FSJ4kDVBgAeRkkg/view?usp=sharing) 環境編譯 [master 分支](https://github.com/KmolYuan/Pyslvs-PyQt5/tree/f00f9af017f865b7172baf73b792eb73cce652a6), 目前無法正確存檔.

Windows 64 位元版本: [pyslvs-18.9.0.mscv1900-amd64.exe](https://drive.google.com/file/d/1PbEYcs71t_wB6L6hm2QKFwQ7KiZww1mX/view?usp=sharing)

# bug

saveAs() missing 1 required positional argument: 'is_branch'

**Comment by KmolYuan** [comment]
已解決：https://github.com/KmolYuan/Pyslvs-PyQt5/commit/965716aa9daee1e7ad29ba37e5c50676691cea55
