### ISSUE TITLE
移動機構點時, 能否保留動態 path 展示, 而非 18.07 版, 確定移動點位置後, 再顯示各點 path

### ISSUE THREAD

**Issue by mdecourse** [pyslvs/pyslvs.github.io#3]
假如是因為某些特定機構無法以三角形疊代,  希望針對能以三角形疊代的案例, 以能動態展示各點 path 的功能.

**Comment by KmolYuan** [comment]
已調整更新時機：https://github.com/KmolYuan/Pyslvs-PyQt5/commit/15335b507669c99b8ab930578ab7f5ad108a34ea

目前面臨 Sketch Solve kernel 沒有即時更新點座標的問題，仍再檢查中。

**Comment by KmolYuan** [comment]
已發現問題為座標點距離使用的判斷並非當前座標而是原始座標。

更新後已解決：https://github.com/KmolYuan/pyslvs/commit/d19a60ce34e100dd524775685dbd68174cc0f118

**Comment by mdecourse** [comment]
Nice, 我編譯試試看, 有問題再回報.

請仔細閱讀 [Introduction to Mechanism Design: with Computer Applications
By Eric Constans, Karl B. Dyer](https://books.google.com.tw/books?id=0A1mDwAAQBAJ&pg=PP1&lpg=PP1&dq=Introduction+to+Mechanism+Design:+with+Computer+Applications&source=bl&ots=WakYIZ-L93&sig=tSRFX6Z9fhaT3Lzk3USgSb05PXA&hl=en&sa=X&ved=2ahUKEwiPqeP4-sPcAhVHFYgKHbE_Ae4Q6AEwBHoECAUQAQ#v=onepage&q=Introduction%20to%20Mechanism%20Design%3A%20with%20Computer%20Applications&f=false) 書中的章節與內容. (on [amazon](https://www.amazon.com/Introduction-Mechanism-Design-Computer-Applications/dp/1138740659/ref=sr_1_1?s=books&ie=UTF8&qid=1532855243&sr=1-1&keywords=linkage+mechanism+design))

這些議題應該就是 Pyslvs 後續開發的方向之一.

**Comment by KmolYuan** [comment]
v18.07 版本陸續進行錯誤修正，主分支現已更新完畢。
