### ISSUE TITLE
目前的滑塊, 能否模擬油壓缸?

### ISSUE THREAD

**Issue by mdecourse** [pyslvs/pyslvs.github.io#6]
能夠模擬 https://youtu.be/ZT0kvHf-dtM 機構中的油壓缸嗎?

**Comment by mdecourse** [comment]
另外, 當模擬特定機構前, 已經有對應 png 或 jpg 等圖檔時, 能否在 canvas 區域, append 對應的機構圖檔?

例如: 模擬 shear press 或 vise grips 時, 能在模擬時貼入對應圖檔.

![shear_press](https://user-images.githubusercontent.com/20835445/43368071-aa4ac868-9389-11e8-9643-93b07d0ca391.png)

![vise_grisp](https://user-images.githubusercontent.com/20835445/43368073-b0f57d5c-9389-11e8-810b-25c1e9f540d9.png)

**Comment by KmolYuan** [comment]
目前尚未支援滑塊作為輸入，可能得在未來的版本更新。

加入機構背景圖應該能近日完成。

**Comment by mdecourse** [comment]
先前貨車後車斗堆高機構範例，是否可以先行導入，至於合成用的氣油壓桿件，能否透過某連桿轉為可變動長度的方式達成？然後將直線轉為壓縮桿的圖示？

**Comment by mdecourse** [comment]
另外，在疊入機構實體圖的同時，必須能讓使用者儘可能定位任一機構點，此一功能完成後，也可能在後續進階版規劃時，以圖層的方式，模仿 類似 V-rep 動態模擬的架構，以簡化的點線元件計算模擬位置，而在畫面中各點及線段，附加上較接近實體的圖檔進行模擬。

**Comment by KmolYuan** [comment]
圖片將作為 VLink optional attributes 的方式加入，包含：

+ bytearray
+ 定位點
+ x y 軸偏移量
+ 順時針旋轉量

若要作為背景圖，可以設定在 ground 連桿。

另外，這些 attributes 僅作為攜帶值，不會參與運算。

**Comment by KmolYuan** [comment]
新增升降機構範例：

![default](https://user-images.githubusercontent.com/10264720/43520845-b8e071fe-95c6-11e8-9605-5335f66ace73.png)

不過當初滑塊表示式只有對**滑槽接地**的連桿做設計，因此目前只有 Python-Solvespace 可以解題（但是此 kernel 在路徑預覽時效能不彰）；而 Pyslvs 屬於無法正確配置三角形的狀態；Sketch Solve 則是角度值會有反轉現象。

滑塊問題解決後，便可正確模擬相關機構：

+ 調整**非接地滑槽**的模擬功能。
+ 配置 triangle functions 的演算法應當改進。
+ Sketch Solve 的滑塊部分模擬應改進。

**Comment by mdecourse** [comment]
因為汽液壓缸的應用範圍非常廣, 目前既有的功能先求穩定後, 再設法納入.

**Comment by KmolYuan** [comment]
基礎的圖片背景支援：

+ https://github.com/KmolYuan/Pyslvs-PyQt5/commit/c2776de4a48699288ce9be037099e67c06381446
+ https://github.com/KmolYuan/Pyslvs-PyQt5/commit/4c231bc2d7a66363e3392e9dc3bd201e39f9eb63

![default](https://user-images.githubusercontent.com/10264720/43686430-11109f14-98f8-11e8-941b-997db9a0cb05.png)

可藉由「Settings」頁簽進行設置，並有基本的 scale 以及 offset 設定，路徑錯誤便不會繪製。

之後將藉由圖片轉存 byte array 繪製連桿，此功能對於拓印尺寸還是有幫助的。

**Comment by mdecourse** [comment]
很棒，稍後再試這個新功能，納入機構實圖的終極目標，是希望能以點、線及多邊形骨幹做為機構運算本體，而2D零件圖形檔則披上各自的骨幹進行模擬，就如同 V-rep 的動態模擬功能。
在此一功能搭配下，在機構模擬時限制特定輸入或輸出的運動範圍，且允許多個輸入致動器同步運動，也是下一步可能納入的功能。
