### ISSUE TITLE
無法存取檔案

### ISSUE THREAD

**Issue by mdecourse** [pyslvs/pyslvs.github.io#7]
https://github.com/KmolYuan/Pyslvs-PyQt5/commit/9784456b5949e3d527a39df7e4148356b091c30d 在 Windows 10 64 位元環境, 設定機構模擬後存檔或取檔均會當機.

**Comment by KmolYuan** [comment]
因為讀取檔案時，解析新式的輸入表示式出錯：https://github.com/KmolYuan/Pyslvs-PyQt5/commit/bd49e3efd67a44ea617eda83e7186267c6216e10

**Comment by mdecourse** [comment]
Good, 這個版本在模擬與尺寸合成已經比較穩定, 但是結構合成若操作不符合原設定流程比較容易當機.

目前利用結構合成可以順利取得多連桿機構的類型, 接下來應該要建立一個固定機構資料庫主機, 用來儲存實際機構分析或合成案例.

建議改版優先順序如下:

1. 能夠匯入機構原型圖檔, 直接在 Pyslvs 檔案中做為參照, 以便從最基本的機構課本範例建立導引教材.
2. 能夠導入汽液壓 piston 作為主動或從動元件, 可以擴增許多既有的連桿範例. (例如: 挖土機, 敞篷車蓋, 啟動平台等)
3. 納入網際機構資料庫伺服與展示架構, 提供遠端機構資料儲存、展示與合成運算.
