### ISSUE TITLE
六連桿模擬問題

### ISSUE THREAD

**Issue by pyslvs** [pyslvs/pyslvs.github.io#8]
當模擬下列 SAM 套件中的範例時:

![2018-08-03_20-24-21](https://user-images.githubusercontent.com/33676306/43642876-c23f0558-975b-11e8-89b0-f40889604d60.png)

以下列機構設定模擬, 無法正確設定主動旋轉連桿:

![pyslvs-18 7 0 mscv1900-amd64_2018-08-03_20-25-36](https://user-images.githubusercontent.com/33676306/43642884-c7e474de-975b-11e8-9361-467749c8a5a3.png)

18.07 連桿檔案壓縮檔:

[sixbar_pyslvs.zip](https://github.com/pyslvs/pyslvs.github.io/files/2257337/sixbar_pyslvs.zip)

**Comment by KmolYuan** [comment]
已修正程式邏輯錯誤：https://github.com/KmolYuan/pyslvs/commit/31d4837a1baf09339bcb577ae34ed2f52ed215f2

**Comment by mdecourse** [comment]
很好，我稍後再測試。接下來要逐一將 Sam 的範例輸入測試，並利用更多的產品開發流程加以驗證，希望將需要納入的新功能一一列出。另外若資訊組有人來，也邀請他們加入 Pyslvs 功能測試的行列，軟體套件透過各方使用回饋，才能愈來愈愈合用。
